module.exports.hero_key_map = {
    'Genji':'genji',
    'D.Va':'dva',
    'McCree':'mccree',
    'Junkrat':'junkrat',
    'Tracer':'tracer',
    'Reaper':'reaper',
    'Moira':'moira',
    'Lúcio':'lucio',
    'Ana':'ana',
    'Widowmaker':'widowmaker',
    'Hanzo':'hanzo',
    'Doomfist':'doomfist',
    'Winston':'winston',
    'Wrecking Ball':'wrecking_ball',
    'Zarya':'zarya',
    'Soldier: 76':'soldier_76',
    'Pharah':'pharah',
    'Reinhardt':'reinhardt',
    'Ashe':'ashe',
    'Zenyatta':'zenyatta',
    'Roadhog':'roadhog',
    'Echo':'echo',
    'Sombra':'sombra',
    'Mercy':'mercy',
    'Baptiste':'baptiste',
    'Mei':'mei',
    'Symmetra':'symmetra',
    'Sigma':'sigma',
    'Bastion':'bastion',
    'Torbjörn':'torbjorn',
    'Brigitte':'brigitte',
    'Orisa':'orisa'
}